import cv2
import numpy as np

if __name__ == '__main__':
    gray=cv2.imread('img\Chew_gray.png',cv2.IMREAD_GRAYSCALE)
    cv2.imshow('gray',gray)
    sobelx=cv2.Sobel(gray,cv2.CV_64F,1,0,ksize=3)
    sobely=cv2.Sobel(gray,cv2.CV_64F,0,1,ksize=3)
    sobelxy=np.sqrt(sobelx**2+sobely**2)
    sobelxy=np.uint8(sobelxy)
    cv2.imshow('sobelxy',sobelxy)
    scharrx=cv2.Scharr(gray,cv2.CV_64F,1,0)
    scharry=cv2.Scharr(gray,cv2.CV_64F,0,1)
    scharrxy=np.sqrt(scharrx**2+scharry**2)
    scharrxy=np.uint8(scharrxy)
    cv2.imshow('scharrxy',scharrxy)
    laplacian=cv2.Laplacian(gray,cv2.CV_64F)
    laplacian=np.uint8(laplacian)
    cv2.imshow('laplacian',laplacian)    
    cv2.waitKey(0)
    cv2.destroyAllWindows()

    
    _,thresh=cv2.threshold(gray,150,255,cv2.THRESH_BINARY)
    cv2.imshow('thresh',thresh)
    sobelx=cv2.Sobel(thresh,cv2.CV_64F,1,0,ksize=3)
    sobely=cv2.Sobel(thresh,cv2.CV_64F,0,1,ksize=3)
    sobelxy=np.sqrt(sobelx**2+sobely**2)
    sobelxy=np.uint8(sobelxy)
    cv2.imshow('sobelxy',sobelxy)
    scharrx=cv2.Scharr(thresh,cv2.CV_64F,1,0)
    scharry=cv2.Scharr(thresh,cv2.CV_64F,0,1)
    scharrxy=np.sqrt(scharrx**2+scharry**2)
    scharrxy=np.uint8(scharrxy)
    cv2.imshow('scharrxy',scharrxy)
    laplacian=cv2.Laplacian(thresh,cv2.CV_64F)
    laplacian=np.uint8(laplacian)
    cv2.imshow('laplacian',laplacian)    
    cv2.waitKey(0)
    cv2.destroyAllWindows()